controllers:
    config:
        body:
            dynamic_reconfigure: True            
        joints:
            dynamic_reconfigure: True
            cascaded_position: False
    tilt:
        velocity: {p: 0.0, i: 0., d: 0.0}
        position: {p: 10, i: 1, d: 0}
    x:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: .1}
    y:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: 0.1}
    z:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: 0}
    roll:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: .1}
    pitch:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: 0.1}
    yaw:
        velocity: {p: 10, i: 1, d: 0.1}
        position: {p: 10, i: 1, d: 0.1}     
            

