controllers:
    config:
        body:
            state: state
            command: thruster_command
            type: thruster
            dynamic_reconfigure: True            
            pid: True
        joints:
            state: joint_states
            setpoint: tilt_command
            command: joint_command
            dynamic_reconfigure: True
            cascaded_position: False
    tilt:
        velocity: {p: 0.0, i: 0., d: 0.0}
        position: {p: 10, i: 1, d: 00}
    x:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 100, i: 5, d: 10}
    y:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 100, i: 5, d: 10}
    z:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 1, i: 0, d: 0}
    roll:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 500, i: 10, d: 1}
    pitch:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 100, i: 5, d: 10}
    yaw:
        velocity: {p: 50, i: 10, d: 0.1}
        position: {p: 100, i: 5, d: 10}      
            

